/**
* Generated by go-doudou v2.5.9.
* You can edit it as your need.
*/
package service

import (
	"context"
	"testdata1/dto"
)
//go:generate go-doudou svc grpc --http2grpc --case 

type Testdata1 interface {
	// You can define your service methods as your need. Below is an example.
	// You can also add annotations here like @role(admin) to add meta data to routes for 
	// implementing your own middlewares
	PostUser(ctx context.Context, user dto.GddUser) (data dto.GddUser, err error)
	PutUser(ctx context.Context, user dto.GddUser) error
	DeleteUser(ctx context.Context, user dto.GddUser) error
	GetUsers(ctx context.Context, parameter dto.Parameter) (data dto.Page, err error)
}
