// Code generated by go generate; DO NOT EDIT.
// This file was generated by go-doudou at
// 2021-06-13 23:22:24.942556 +0800 CST m=+0.002601776
package testfiles

import (
	"encoding/json"

	"github.com/unionj-cloud/go-doudou/name/strategies"
)

func (object PageFilter) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	objectMap[strategies.LowerCaseConvert("Name")] = object.Name
	objectMap[strategies.LowerCaseConvert("Dept")] = object.Dept
	return json.Marshal(objectMap)
}

func (object Order) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	objectMap[strategies.LowerCaseConvert("Col")] = object.Col
	objectMap[strategies.LowerCaseConvert("Sort")] = object.Sort
	return json.Marshal(objectMap)
}

func (object PageRet) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	objectMap[strategies.LowerCaseConvert("Items")] = object.Items
	objectMap[strategies.LowerCaseConvert("PageNo")] = object.PageNo
	objectMap[strategies.LowerCaseConvert("PageSize")] = object.PageSize
	objectMap[strategies.LowerCaseConvert("Total")] = object.Total
	objectMap[strategies.LowerCaseConvert("HasNext")] = object.HasNext
	return json.Marshal(objectMap)
}
