package strategies

import (
	"cloud/unionj/papilio/kit/stringutils"
	"text/template"
	"unicode"
)

var LowerCaseNamingStrategyTemplate = template.Must(template.New("").Parse(templ))

func init() {
	Registry["lowerCaseNamingStrategy"] = LowerCaseNamingStrategyTemplate
}

func LowerCaseConvert(key string) (result string) {
	if stringutils.IsEmpty(key) {
		return
	}
	result = string(unicode.ToLower(rune(key[0]))) + key[1:]
	return
}

const templ = `// Code generated by go generate; DO NOT EDIT.
// This file was generated by papilio at
// {{ .Timestamp }}
package {{ .StructCollector.Package.Name }}

import (
	"encoding/json"
	"cloud/unionj/papilio/kit/namingstrategy/strategies"
)

{{ range $struct := .StructCollector.Structs }}
func (object {{$struct.Name}}) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	{{- range $field := $struct.Fields}}
	{{- if ne $field.Type "embed"}}
	objectMap[strategies.LowerCaseConvert("{{$field.Name}}")] = object.{{$field.Name}}
	{{- else}}
	data, err := json.Marshal(object.{{$field.Name}})
	if err != nil {
		panic(err)
	}
	_objectMap := make(map[string]interface{})
	err = json.Unmarshal(data, &_objectMap)
	if err != nil {
		panic(err)
	}
    for k, v :=range _objectMap {
		if _, exists := objectMap[k]; !exists {
			objectMap[k] = v
		}
	}
	{{- end }}
	{{- end }}
	return json.Marshal(objectMap)
}
{{ end }}
`
