/**
* Generated by go-doudou v2.0.4.
* Don't edit!
*/
package client

import (
	"context"
	"github.com/go-resty/resty/v2"
	"testdata/vo"
	"testdata/dto"
	v3 "github.com/unionj-cloud/toolkit/openapi/v3"
	"os"
)

type Options struct {
	GzipReqBody bool
}

type IUsersvcClient interface {
	PageUsers(ctx context.Context, _headers map[string]string,query vo.PageQuery,, options Options) (_resp *resty.Response,code int,data vo.PageRet,msg error)
	GetUser(ctx context.Context, _headers map[string]string,userId string,photo string,, options Options) (_resp *resty.Response,code int,data string,msg error)
	SignUp(ctx context.Context, _headers map[string]string,username string,password int,actived bool,score []int,, options Options) (_resp *resty.Response,code int,data string,msg error)
	UploadAvatar(ctx context.Context, _headers map[string]string,pf []v3.FileModel,ps string,pf2 v3.FileModel,pf3 *multipart.FileHeader,pf4 []*multipart.FileHeader,, options Options) (_resp *resty.Response,ri int,ri2 interface{},re error)
	DownloadAvatar(ctx context.Context, _headers map[string]string,userId interface{},data []byte,price decimal.Decimal,userAttrs ...string,, options Options) (_resp *resty.Response,rf *os.File,re error)
	GetQuery_range(ctx context.Context, _headers map[string]string,, options Options) (_resp *resty.Response,re error)
	GetShelves_ShelfBooks_Book(ctx context.Context, _headers map[string]string,, options Options) (_resp *resty.Response,re error)
}