// Code generated by go generate; DO NOT EDIT.
// This file was generated by papilio at
// 2021-02-14 20:05:38.052657 +0800 CST m=+0.001253606
package vo

import (
	"encoding/json"
	"cloud/unionj/papilio/kit/namingstrategy/strategies"
)


func (object Student) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	objectMap[strategies.LowerCaseConvert("Name")] = object.Name
	objectMap[strategies.LowerCaseConvert("Age")] = object.Age
	objectMap[strategies.LowerCaseConvert("TestScore")] = object.TestScore
	data, err := json.Marshal(object.School)
	if err != nil {
		panic(err)
	}
	_objectMap := make(map[string]interface{})
	err = json.Unmarshal(data, &_objectMap)
	if err != nil {
		panic(err)
	}
    for k, v :=range _objectMap {
		if _, exists := objectMap[k]; !exists {
			objectMap[k] = v
		}
	}
	return json.Marshal(objectMap)
}

func (object School) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	objectMap[strategies.LowerCaseConvert("Name")] = object.Name
	objectMap[strategies.LowerCaseConvert("Address")] = object.Address
	objectMap[strategies.LowerCaseConvert("CreateAt")] = object.CreateAt
	return json.Marshal(objectMap)
}

