/**
* Generated by go-doudou v2.5.9.
* You can edit it as your need.
 */
package test

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-resty/resty/v2"
	_querystring "github.com/google/go-querystring/query"
	"github.com/opentracing-contrib/go-stdlib/nethttp"
	"github.com/opentracing/opentracing-go"
	"github.com/pkg/errors"
	"github.com/unionj-cloud/go-doudou/v2/framework/registry"
	"github.com/unionj-cloud/go-doudou/v2/framework/restclient"
	v3 "github.com/unionj-cloud/toolkit/openapi/v3"
)

type UploadClient struct {
	provider registry.IServiceProvider
	client   *resty.Client
	rootPath string
}

func (receiver *UploadClient) SetRootPath(rootPath string) {
	receiver.rootPath = rootPath
}

func (receiver *UploadClient) SetProvider(provider registry.IServiceProvider) {
	receiver.provider = provider
}

func (receiver *UploadClient) SetClient(client *resty.Client) {
	receiver.client = client
}

// PostUploadAvatar UploadAvatar demonstrate how to define upload files api
// there must be one []v3.FileModel or v3.FileModel parameter among input parameters
// remember to close the readers by Close method of v3.FileModel if you don't need them anymore when you finished your own business logic
func (receiver *UploadClient) PostUploadAvatar(ctx context.Context, _headers map[string]string,
	bodyParams struct {
		// required
		Ps string `json:"ps" url:"ps"`
	},
	pf []v3.FileModel) (ret UploadAvatarResp, _resp *resty.Response, err error) {
	var _err error

	_req := receiver.client.R()
	_req.SetContext(ctx)
	if len(_headers) > 0 {
		_req.SetHeaders(_headers)
	}
	_bodyParams, _ := _querystring.Values(bodyParams)
	_req.SetFormDataFromValues(_bodyParams)
	if len(pf) == 0 {
		err = errors.New("at least one file should be uploaded for parameter pf")
		return
	}
	for _, _f := range pf {
		_req.SetFileReader("pf", _f.Filename, _f.Reader)
	}

	_resp, _err = _req.Post("/upload/avatar")
	if _err != nil {
		err = errors.Wrap(_err, "")
		return
	}
	if _resp.IsError() {
		err = errors.New(_resp.String())
		return
	}
	if _err = json.Unmarshal(_resp.Body(), &ret); _err != nil {
		err = errors.Wrap(_err, "")
		return
	}
	return
}

// PostUploadAvatar2 UploadAvatar2 demonstrate how to define upload files api
// remember to close the readers by Close method of v3.FileModel if you don't need them anymore when you finished your own business logic
func (receiver *UploadClient) PostUploadAvatar2(ctx context.Context, _headers map[string]string,
	bodyParams struct {
		// required
		Ps string `json:"ps" url:"ps"`
	},
	pf []v3.FileModel,
	pf2 *v3.FileModel,
	pf3 *v3.FileModel) (ret UploadAvatar2Resp, _resp *resty.Response, err error) {
	var _err error

	_req := receiver.client.R()
	_req.SetContext(ctx)
	if len(_headers) > 0 {
		_req.SetHeaders(_headers)
	}
	_bodyParams, _ := _querystring.Values(bodyParams)
	_req.SetFormDataFromValues(_bodyParams)
	if len(pf) == 0 {
		err = errors.New("at least one file should be uploaded for parameter pf")
		return
	}
	for _, _f := range pf {
		_req.SetFileReader("pf", _f.Filename, _f.Reader)
	}
	if pf2 != nil {
		_req.SetFileReader("pf2", pf2.Filename, pf2.Reader)
	}
	if pf3 != nil {
		_req.SetFileReader("pf3", pf3.Filename, pf3.Reader)
	}

	_resp, _err = _req.Post("/upload/avatar/2")
	if _err != nil {
		err = errors.Wrap(_err, "")
		return
	}
	if _resp.IsError() {
		err = errors.New(_resp.String())
		return
	}
	if _err = json.Unmarshal(_resp.Body(), &ret); _err != nil {
		err = errors.Wrap(_err, "")
		return
	}
	return
}

func NewUpload(opts ...restclient.RestClientOption) *UploadClient {
	defaultProvider := restclient.NewServiceProvider("UPLOAD")
	defaultClient := restclient.NewClient()

	svcClient := &UploadClient{
		provider: defaultProvider,
		client:   defaultClient,
	}

	for _, opt := range opts {
		opt(svcClient)
	}

	svcClient.client.OnBeforeRequest(func(_ *resty.Client, request *resty.Request) error {
		request.URL = svcClient.provider.SelectServer() + svcClient.rootPath + request.URL
		return nil
	})

	svcClient.client.SetPreRequestHook(func(_ *resty.Client, request *http.Request) error {
		traceReq, _ := nethttp.TraceRequest(opentracing.GlobalTracer(), request,
			nethttp.OperationName(fmt.Sprintf("HTTP %s: %s", request.Method, request.URL.Path)))
		*request = *traceReq
		return nil
	})

	svcClient.client.OnAfterResponse(func(_ *resty.Client, response *resty.Response) error {
		nethttp.TracerFromRequest(response.Request.RawRequest).Finish()
		return nil
	})

	return svcClient
}
