/**
* Generated by go-doudou v2.5.9.
* You can edit it as your need.
*/
package dto

//go:generate go-doudou name --file $GOFILE --form --case 

type GddUser struct {
	Id    int64
	Name  string
	Phone string
	Dept  string
}

// Page result wrapper
type Page struct {
	Items      []interface{}
	Page       int64
	Size       int64
	MaxPage    int64
	TotalPages int64
	Total      int64
	Last       bool
	First      bool
	Visible    int64
}

// Parameter struct
type Parameter struct {
	Page    int64
	Size    int64
	Sort    string
	Order   string
	Fields  string
	Filters string
}

func (receiver Parameter) GetPage() int64 {
	return receiver.Page
}

func (receiver Parameter) GetSize() int64 {
	return receiver.Size
}

func (receiver Parameter) GetSort() string {
	return receiver.Sort
}

func (receiver Parameter) GetOrder() string {
	return receiver.Order
}

func (receiver Parameter) GetFields() string {
	return receiver.Fields
}

func (receiver Parameter) GetFilters() interface{} {
	return receiver.Filters
}

func (receiver Parameter) IParameterInstance() {

}
