package codegen

import (
	log "github.com/sirupsen/logrus"
	"github.com/unionj-cloud/go-doudou/v2/cmd/internal/astutils"
	"github.com/unionj-cloud/go-doudou/v2/toolkit/templateutils"
	"github.com/unionj-cloud/go-doudou/v2/version"
	"os"
	"path/filepath"
	"strings"
)

var entityTmpl = `/**
* Generated by go-doudou {{.Version}}.
* You can edit it as your need.
*/
package entity

import (
	"time"

	"github.com/shopspring/decimal"
)

//dd:table
type {{.Name}} struct {
{{- range $f := .Fields }}
	{{$f.Name}} {{$f.Type}} ` + "`" + `{{$f.Tag}}` + "`" + `
{{- end }}
}`

// GenEntityGo generates structs code in entity pkg from database tables
func GenEntityGo(dpath string, entity astutils.StructMeta) error {
	var (
		err error
		f   *os.File
	)
	_ = os.MkdirAll(dpath, os.ModePerm)
	dfile := filepath.Join(dpath, strings.ToLower(entity.Name)+".go")
	if _, err = os.Stat(dfile); os.IsNotExist(err) {
		f, _ = os.Create(dfile)
		defer f.Close()
		var source string
		entity.Version = version.Release
		source, _ = templateutils.String("entity.go.tmpl", entityTmpl, entity)
		astutils.FixImport([]byte(source), dfile)
	} else {
		log.Warnf("file %s already exists", dfile)
	}
	return nil
}
