// Code generated by go generate; DO NOT EDIT.
// This file was generated by go-doudou at
// 2021-04-13 14:24:19.898953 +0800 CST m=+0.001608949
package vo

import (
	"encoding/json"
	"github.com/unionj-cloud/go-doudou/name/strategies"
)


func (object Student) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	objectMap[strategies.LowerCaseConvert("School")] = object.School
	objectMap[strategies.LowerCaseConvert("Company")] = object.Company
	objectMap[strategies.LowerCaseConvert("Name")] = object.Name
	objectMap[strategies.LowerCaseConvert("Age")] = object.Age
	objectMap[strategies.LowerCaseConvert("TestScore")] = object.TestScore
	objectMap[strategies.LowerCaseConvert("IsPaid")] = object.IsPaid
	return json.Marshal(objectMap)
}

func (object School) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	objectMap[strategies.LowerCaseConvert("Name")] = object.Name
	objectMap[strategies.LowerCaseConvert("Address")] = object.Address
	objectMap[strategies.LowerCaseConvert("CreateAt")] = object.CreateAt
	return json.Marshal(objectMap)
}

func (object Company) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	objectMap[strategies.LowerCaseConvert("Name")] = object.Name
	objectMap[strategies.LowerCaseConvert("Biz")] = object.Biz
	objectMap[strategies.LowerCaseConvert("CreateAt")] = object.CreateAt
	return json.Marshal(objectMap)
}

